# print("Assalom aleykum!")
# print("Hi guys")
print("lorem ipsum")
print('Men "Lenovo" markasidagi kompyuter ishlataman.')
print("Men \'Samsung\' markazidagi telfon ishlataman")
print('Men \'iPhone\' markazidagi telfon ishlataman')
print("Odami ersang, demagil odami, \n Oniki, yo'q xalq g'amidin g'ami")
# Arifmetik amallar
print(5 + 6)
print(10 - 6)
print(18 * 6)
print(20 / 4, 15 / 3, 24 /6)
print(15 // 7)
print(20 // 5)
print(5 ** 12, 12 ** 2)
print(64 ** (1 / 2))
print(625 ** (1 / 4))
print(12 % 5)
print(4 % 7) #4 
print(5 % 6) #5
print("Beshning kvadrati", 5 ** 2, "ga teng" )
print('3x3=',3*3)
# Amaliyot 
print(" \"Nexia\", \"Tico\", 'Damas' ko'rganlar qilar havas")
print('"Nexia", "Tico", \'Damas\' ko\'rganlar qilar havas')
print("5-ning 4-darajasi", 5 ** 4)
print("22 ni 4 ga bo'lganda qoldiq", 22 % 4)
print("Tomonlari 125 ga teng kvadratning yuzi" , 125 ** 2, "va perimetri", 125 * 4)
print("Diametri 12 ga teng bo'lgan doiraning yuzi", 12 / 6, "kvadrati", (6 ** 2) * 3.14 ) 
print("Tomonlari 3, 4, 5, ga teng bo'lgan uchburchakning yuzasi",(6 * (6 - 3) * (6 - 4) * (6 - 5)) ** (1 / 2), "ga teng")